# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' list alleles and the read id that supports them at a given pos
#'
#' @export
pileup_readid <- function(bam_path, seqname, pos) {
    .Call(`_RcppPileup_pileup_readid`, bam_path, seqname, pos)
}

