# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
variant_count_matrix_cpp <- function(bam_path, seqname, pos, indel, barcodes) {
    .Call(`_RcppPileup_variant_count_matrix_cpp`, bam_path, seqname, pos, indel, barcodes)
}

